# Boolean Masking

In [1]:
import numpy as np

In [3]:
npa = np.array([-1, 1, -2, 2, -3, 3])
npa

array([-1,  1, -2,  2, -3,  3])

In [4]:
np.less(npa, 0)

array([ True, False,  True, False,  True, False])

In [5]:
npa < 0

array([ True, False,  True, False,  True, False])

In [6]:
mask = npa > 0

In [7]:
mask

array([False,  True, False,  True, False,  True])

In [8]:
npa[mask]

array([1, 2, 3])

In [9]:
npb = np.arange(-5, 6)
npb

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5])

In [11]:
mask1 = (npb > 0) & (npb < 4)
mask1

array([False, False, False, False, False, False,  True,  True,  True,
       False, False])

In [12]:
npb[mask1]

array([1, 2, 3])