# Creating Array from Scratch

np.zeros -> arrays filled with zeros\
np.ones  -> arrays filled with ones\
np.full  -> arrays filled with some specified constant value\
np.eye   -> generates identity matrices\
np.arange -> generates 1-D array based on a range [start:stop:step]\
np.linspace -> generates evenly spaced number between start/stop\
np.random.random -> arryas filled with random floats [0, 1]

In [1]:
import numpy as np

In [2]:
a = np.zeros(5)

In [3]:
a

array([0., 0., 0., 0., 0.])

In [4]:
a.dtype

dtype('float64')

In [5]:
a = np.zeros(5, dtype=np.int32)

In [6]:
a

array([0, 0, 0, 0, 0])

In [7]:
a.dtype

dtype('int32')

In [8]:
a = np.zeros((4, 3), dtype=np.uint8)
a

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=uint8)

In [9]:
m = np.ones((10, 2), dtype=float)
m

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [10]:
m = np.full((2, 5), 3.14, dtype=np.float32)
m

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]], dtype=float32)

In [12]:
m = np.eye(5, dtype=np.int32)
m

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [14]:
m = np.eye(5, 3, dtype=np.uint16)
m

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 0],
       [0, 0, 0]], dtype=uint16)

In [18]:
np.arange(2, 11, 2, dtype=int)

array([ 2,  4,  6,  8, 10])

In [19]:
np.linspace(2, 10, num=5)

array([ 2.,  4.,  6.,  8., 10.])

In [20]:
np.linspace(2, 10, num=10)

array([ 2.        ,  2.88888889,  3.77777778,  4.66666667,  5.55555556,
        6.44444444,  7.33333333,  8.22222222,  9.11111111, 10.        ])

In [21]:
import math

In [22]:
x_coords = np.linspace(-2 * math.pi, 2 * math.pi, 50)
x_coords

array([-6.28318531, -6.02672876, -5.77027222, -5.51381568, -5.25735913,
       -5.00090259, -4.74444605, -4.48798951, -4.23153296, -3.97507642,
       -3.71861988, -3.46216333, -3.20570679, -2.94925025, -2.6927937 ,
       -2.43633716, -2.17988062, -1.92342407, -1.66696753, -1.41051099,
       -1.15405444, -0.8975979 , -0.64114136, -0.38468481, -0.12822827,
        0.12822827,  0.38468481,  0.64114136,  0.8975979 ,  1.15405444,
        1.41051099,  1.66696753,  1.92342407,  2.17988062,  2.43633716,
        2.6927937 ,  2.94925025,  3.20570679,  3.46216333,  3.71861988,
        3.97507642,  4.23153296,  4.48798951,  4.74444605,  5.00090259,
        5.25735913,  5.51381568,  5.77027222,  6.02672876,  6.28318531])

In [23]:
y_values = np.array([ math.sin(x) for x in x_coords])
y_values

array([ 2.44929360e-16,  2.53654584e-01,  4.90717552e-01,  6.95682551e-01,
        8.55142763e-01,  9.58667853e-01,  9.99486216e-01,  9.74927912e-01,
        8.86599306e-01,  7.40277997e-01,  5.45534901e-01,  3.15108218e-01,
        6.40702200e-02, -1.91158629e-01, -4.33883739e-01, -6.48228395e-01,
       -8.20172255e-01, -9.38468422e-01, -9.95379113e-01, -9.87181783e-01,
       -9.14412623e-01, -7.81831482e-01, -5.98110530e-01, -3.75267005e-01,
       -1.27877162e-01,  1.27877162e-01,  3.75267005e-01,  5.98110530e-01,
        7.81831482e-01,  9.14412623e-01,  9.87181783e-01,  9.95379113e-01,
        9.38468422e-01,  8.20172255e-01,  6.48228395e-01,  4.33883739e-01,
        1.91158629e-01, -6.40702200e-02, -3.15108218e-01, -5.45534901e-01,
       -7.40277997e-01, -8.86599306e-01, -9.74927912e-01, -9.99486216e-01,
       -9.58667853e-01, -8.55142763e-01, -6.95682551e-01, -4.90717552e-01,
       -2.53654584e-01, -2.44929360e-16])

In [24]:
np.random.random(5)

array([0.60529781, 0.09435017, 0.80984959, 0.40648392, 0.50561512])

In [25]:
np.random.seed(0)
np.random.random(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [26]:
np.random.random((5, 3))

array([[0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504],
       [0.52889492, 0.56804456, 0.92559664],
       [0.07103606, 0.0871293 , 0.0202184 ],
       [0.83261985, 0.77815675, 0.87001215]])

In [27]:
np.random.randint(1, 10, 50)

array([3, 4, 9, 2, 4, 4, 4, 8, 1, 2, 1, 5, 8, 4, 3, 8, 3, 1, 1, 5, 6, 6,
       7, 9, 5, 2, 5, 9, 2, 2, 8, 4, 7, 8, 3, 1, 4, 6, 5, 5, 7, 5, 5, 4,
       5, 5, 9, 5, 4, 8])

In [28]:
from numpy import random as npr

In [29]:
npr.seed(0)
npr.randint(1, 6 + 1, 10)

array([5, 6, 1, 4, 4, 4, 2, 4, 6, 3])

In [30]:
npr.seed(0)
npr.randint(1, 7, (10, 2))

array([[5, 6],
       [1, 4],
       [4, 4],
       [2, 4],
       [6, 3],
       [5, 1],
       [1, 5],
       [3, 2],
       [1, 2],
       [6, 2]])