# Fancy Indexing

In [1]:
import numpy as np

In [2]:
npa = np.arange(1, 26).reshape(5, 5)
npa

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [3]:
npa[1, np.array([0, 1, 3])]

array([6, 7, 9])

In [6]:
npa[np.array([0, 1, 3]), 1]

array([ 2,  7, 17])

In [7]:
npa[1:3, np.array([0, 1, 3])]

array([[ 6,  7,  9],
       [11, 12, 14]])

In [8]:
npa[:, np.array([0, 3])]

array([[ 1,  4],
       [ 6,  9],
       [11, 14],
       [16, 19],
       [21, 24]])