ndarray
- fixed size
- can be reshaped
- homogeneous
- elements have specialized, restricted data types
- indexing arr[i]
- slicing arr[a:b:c]
- masking arr[(arr > 2) & (arr < 10)]
- fancy indexing arr[[0, 3, 4]]

NumPy Efficiency
- More space efficient than Python
- Array manipulation and calculations are must faster (vectorization)
- But at a cost
  - fixed size  
    -> once created, cannot add/remove elements  
    -> elements can be replaces
  - homogeneous  
    -> all elements must be the same type  
  - data types  
    -> it uses data types from underlyig C language  
    -> memory efficiency & vectorization  

## Creating Array from Lists

In [1]:
import numpy as np

In [14]:
a1 = np.array([1, 2, 3, 4])
a2 = np.array((0.1, 0.2, 0.3, 0.4))
a3 = np.array([1, 2, 3, 4], dtype=np.uint8)

In [15]:
a1

array([1, 2, 3, 4])

In [16]:
type(a1)

numpy.ndarray

In [17]:
a2

array([0.1, 0.2, 0.3, 0.4])

In [18]:
type(a2)

numpy.ndarray

In [19]:
a1.dtype

dtype('int32')

In [20]:
a2.dtype

dtype('float64')

In [22]:
a3

array([1, 2, 3, 4], dtype=uint8)

In [23]:
a3.dtype

dtype('uint8')

In [24]:
m2 = np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
        [10, 11, 12]
    ]
)
   

In [25]:
m2.size

12

In [26]:
m2.shape

(4, 3)