# Numpy Indexing

In [1]:
import numpy as np

In [2]:
npa = np.array([1, 2, 3, 4, 5])
npa

array([1, 2, 3, 4, 5])

In [3]:
npa[3] = 500
npa

array([  1,   2,   3, 500,   5])

## 2 dimensions arrays

In [4]:
m1 = np.eye(3)
m1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [6]:
m1[1, 2] = 9.2
m1

array([[1. , 0. , 0. ],
       [0. , 1. , 9.2],
       [0. , 0. , 1. ]])

In [8]:
m1[1, 2]

9.2