# Reshaping Arrays

In [1]:
import numpy as np

In [2]:
arr = np.arange(12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
arr.shape

(12,)

In [4]:
m1 = arr.reshape(4, 3)
m1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [6]:
m2 = arr.reshape(2, 6)
m2

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [7]:
m3 = arr.reshape(6, 2)
m3

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [ ]:
arr[0] = 100
print(arr)
print(m1)
print(m2)
print(m3)

## Make a copy so the original array will not get affected

In [13]:
m4 = arr.reshape(3, 4).copy()
m4

array([[100,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11]])

In [14]:
m4[0][0] = 555

In [15]:
m4

array([[555,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11]])

In [16]:
arr

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11])