# Numpy Slicing

In [1]:
import numpy as np

In [2]:
npa = np.array([1, 2, 3, 4, 5, 6])
npa

array([1, 2, 3, 4, 5, 6])

In [3]:
m1 = npa[0::2]
m1

array([1, 3, 5])

In [4]:
npb = np.arange(1, 7)
npb

array([1, 2, 3, 4, 5, 6])

In [5]:
npb[-1] = 60
npb

array([ 1,  2,  3,  4,  5, 60])

## Dimensions Arrays

In [8]:
npc = np.arange(1, 26).reshape(5, 5)
npc

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [10]:
npc[0:3, 0:2]

array([[ 1,  2],
       [ 6,  7],
       [11, 12]])

In [12]:
npc[::3, ::2]

array([[ 1,  3,  5],
       [16, 18, 20]])

In [13]:
npc[2, 1::2]

array([12, 14])