# Stacking Arrays

In [1]:
import numpy as np

In [2]:
a1 = np.arange(1, 6)
a1

array([1, 2, 3, 4, 5])

In [3]:
a2 = np.arange(1, 11).reshape(2, 5)
a2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [4]:
vstack1 = np.vstack((a1, a2))
vstack1

array([[ 1,  2,  3,  4,  5],
       [ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

## Stacking with different type

In [5]:
np1 = np.array((1, 2, 3, 4))
np2 = np.array([0.1, 0.2, 0.3, 0.4])
result = np.vstack((np1, np2))
result

array([[1. , 2. , 3. , 4. ],
       [0.1, 0.2, 0.3, 0.4]])

In [6]:
result.dtype

dtype('float64')